- fastquant/strategies.py
Implementation reference (simplified):
https://www.backtrader.com/blog/posts/2016-07-30-macd-settings/macd-settings/
> Add MACD strategy based on backtrader sample to close issue #16

- .flake8
- .pre-commit-config.yaml
- examples/jfc_rsi.py
- examples/jfc_support_resistance.py
- fastquant/fastquant.py
- fastquant/strategies.py
- pyproject.toml
- requirements.txt
- setup.py
I learned that everyone uses black as code formatter. Here, I added flake8 as code checker. For convenience, I also added both black and flake8 in the pre-commit hooks. See [LJ's blog for details](https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/). 
Let me know if it works for you.
> add flake8 checker and pre-commit hook for black and flake8

- CONTRIBUTING.md
Added details in contibuting.md
> edit contributing.md

- fastquant/strategies.py
This pull request adds the `EMACStrategy` class by inheriting the `BaseStrategy`
> Add EMA strategy class

- fastquant/strategies.py
This *bollinger band strategy* assumes that the stock will be purchased when the closing price is below the lower band (treat as support), and to be sold when the closing price is above the upper band (treat as resistance).
> Add naive bollinger band strategy

- R/NAMESPACE
- R/R/get-pse.R
API endpoints were added in the following manner:
```
if (paste0("http://1.phisix-api.appspot.com/stocks/", # check if new API is null
symbol, ".", date, ".json") %>%
GET() %>%
content(type="application/json") %>%
is.null()) {
req <- paste0("http://phisix-api.appspot.com/stocks/", # if null move to old API
symbol, ".", date, ".json") %>%
GET() %>%
content(type="application/json")
} else {
req <- paste0("http://1.phisix-api.appspot.com/stocks/", 
symbol, ".", date, ".json") %>%
GET() %>%
content(type="application/json")
}
```
Since we're making the GET request three times it slows the process down. Would like to know how to make this implementation better.
> Link new API endpoint

- fastquant/strategies.py
- tests/test_strategies.py
Fix to #65 . Before merging, help me to suppress cerebro stdout when `verbose=False` in `backtest`. Related documentation here: https://www.backtrader.com/docu/writer/ but not sure how to do this correctly.
> change return of backtest

- fastquant/fastquant.py
> Set dt as index for easier plotting

- fastquant/strategies.py
Added the buy and hold strategy that will be used as the baseline comparison for other strategies. It basically "buys" the afforded size on the start date, and sells the entire position on the end date.
> Buy and hold v1

- fastquant/strategies.py
solves #89 
notebook: https://colab.research.google.com/drive/1TEJDLxlxSqDBghlJplbN2PWmktXpWPrI?usp=sharing
> add fix for colab plotting

- CONTRIBUTING.md
Updated location of requirements.txt. Fixed typo in fastquant/pull_requests link
> CONTRIBUTING.md quick fixes 

- python/tests/test_strategies.py
> fix pytest build for senti-strat

- python/fastquant/__init__.py
- python/fastquant/portfolio.py
- python/requirements.txt
- python/tests/test_portfolio.py
* added basic portfolio class based on this [colab](https://colab.research.google.com/drive/14SnvOTF4Bwq8qP68988GlIVNRZFEyOwx?usp=sharing&hl=en#scrollTo=TANBEK209Src)
> Portfolio2

- python/fastquant/fastquant.py
- python/tests/test_fastquant.py
This PR aims to fix issue #161.
> Return None in get_pse_data when symbol not cached

- python/fastquant/strategies.py
This PR should resolve issue #164
> Add commission_per_transaction as argument

- python/fastquant/crypto.py
- python/fastquant/fastquant.py
- python/tests/test_fastquant.py
Add support for a couple of crypto exchanges and make it easy to add more by appending to a list
> Support addt'l crypto exchanges 

- python/fastquant/disclosures/pse.py
- python/fastquant/network.py
This PR just removes a line in network.py `pl.style.use('fivethirtyeight')` to fix issue #183
> remove style in network

- python/fastquant/backtest/backtest.py
- python/tests/test_strategies.py
This PR should resolve issue #200 where an error related to a duplicate commission key occurs.
> Fix commission error when doing grid search

- .travis.yml
- README.md
> R Travis check

- python/fastquant/data/stocks/pse.py
Function get_pse_all_stocks() in pse.py
> Get available PSE stock symbols #126

- README.md
> Recommend installing with python interpreter

- python/fastquant/backtest/backtest.py
- python/fastquant/strategies/base.py
This resolves #314.
Note that one exception is `data_class` since there seems to be no "falsey" class that's straightforward. I don't think this will be an issue as well.
> Make falsey defaults w same type to resolve #314

- python/fastquant/data/web/twitter.py
> Updated twitter.py: Added missing imports

- python/fastquant/backtest/backtest.py
- python/fastquant/backtest/post_backtest.py
- python/fastquant/strategies/macd.py
The macd's docstring does not describe the arguments of the strategy. Fix the arguments
> Fix macd doc

- README.md
- python/fastquant/strategies/base.py
- python/fastquant/strategies/macd.py
Fix the parameters of macd in README.md
> Fix readme

- python/fastquant/backtest/backtest.py
- python/fastquant/backtest/post_backtest.py
- python/fastquant/strategies/base.py
resolves #
- Stop loss and take profit works fine for only trader at a time
- I temporarily removed stop_trail to easily deal with the problem in stoploss. I'll add it if there were no bugs occured
> Fixed Stoploss and Take profit feature

- python/scripts/update_cache
resolves #366 
This fixes the issue by running the script `update_data_cache` i.e. update cache is committed.
The import bug in `update pse_data_cache` is also fixed.
> fix script import bug & update pse data cache

- python/fastquant/data/stocks/pse.py
- python/fastquant/disclosures/investagrams.py
- python/fastquant/disclosures/pse.py
resolves #421 
The import statement for json_normalize has been updated.
> Updated Import Source of json_normalize
