enzoampil/fastquant

- fastquant/disclosures.py
@jpdeleon Multi page disclosure querying should work now, by identifying the number of pages in the results and looping through each of the pages.
Sampe code (2 pages):
```
DATE_START = "01-01-2018"
DATE_END = "12-01-2019"
cd = DisclosuresPSE(
symbol=PHISIX_SYMBOL, start_date=DATE_START, end_date=DATE_END
)
cd.company_disclosures.shape
```
> Disclosure pagination

- fastquant/disclosures.py
###Problem Description:
[ISSUES-85](https://github.com/enzoampil/fastquant/issues/85)
use instead [flatnonzero](https://docs.scipy.org/doc/numpy/reference/generated/numpy.flatnonzero.html)
```python
idxs1 = np.flatnonzero(older)
```
Python 3.6.9
numpy 1.18.0
pandas 1.0.3
> [ISSUES-85] Replace numpy argswhere with flatnonzero

- python/fastquant/disclosures.py
Raises a warning and prints instruction to use `DisclosuresPSE` class instead of `get_company_disclosures` function
> add deprecation warning

- .flake8
- python/fastquant/fastquant.py
- python/fastquant/indicators.py
- python/fastquant/strategies.py
- python/tests/test_strategies.py
This PR Generalizes the `SentimentStrategy` to be compatible with Disclosures and Twitter
Notable Changes in the repo:
`strategies.py`
added a Custom `SentimentDF` class which extends `PandasData` datafeed to have `sentiment_score` column which can then be accessed inside via `self.data.sentiment_score`
changed `get_bt_news` to `get_bt_news_sentiment` to make it more transparent to the user.
more info in collab [link](https://colab.research.google.com/drive/1ahl0o7BBR1ULhM8e6blcSt7_BniFnTXb?usp=sharing)
> refactor sentiment strat

- README.md
- python/fastquant/fastquant.py
- python/requirements.txt
- python/tests/test_fastquant.py
**This PR adds the `get_crypto_data` function which returns crypto data from binance in OHLCV format.**
This should resolve issue #92 and you can test it out in this colab [link](https://colab.research.google.com/drive/1uJToo_8BcyQ38N39XqQKw4lwvoKFnAO1?usp=sharing).
Sample usage:
```
!pip install -e git+git://github.com/enzoampil/fastquant.git@add_crypto#egg=fastquant
from fastquant import get_crypto_data
crypto = get_crypto_data("BTC/USDT", "2018-12-01", "2019-12-31")
crypto
open    high     low     close    volume
dt                                                          
2018-12-01  4041.27  4299.99  3963.01  4190.02  44840.073481
2018-12-02  4190.98  4312.99  4103.04  4161.01  38912.154790
2018-12-03  4160.55  4179.00  3827.00  3884.01  49094.369163
2018-12-04  3884.76  4085.00 …
```
> Add crypto via get_crypto_data

- python/fastquant/backtest/backtest.py
- python/fastquant/config.py
This PR which should resolve issue #83 allows for the data format of a dataframe used as an input in `backtest` to be automatically inferred based on the column names. Detectable column names can be found as keys in `config.DATA_FORMAT_BASE` (aside from `dt`).
@jpdeleon mind reviewing since we were the ones working this before? :smile:
> Dynamic data format without specifying data_format in `backtest`

- python/fastquant/backtest/backtest.py
- python/fastquant/config.py
- python/fastquant/indicators/custom.py
- python/fastquant/strategies/__init__.py
- python/fastquant/strategies/base.py
- python/fastquant/strategies/custom.py
- python/tests/test_strategies.py
**Goal:** Users should be able to use forecasts (independent of stats / ML model used) as indicators to be used for backtesting
1. **Users can utilize a new `"custom"` strategy in `backtest` that implements a chosen dataframe column (`custom_column`) as a custom indicator (column name set as "custom" by default).**
The strategy is structured similar to `RSIStrategy` where you can set an `upper_limit`, above which the asset is sold (considered "overbought"), and a `lower_limit`, below which the asset is sold (considered "underbought). `upper_limit` is set to 95 by default, while `lower_limit` is set to 5 by default.
2. **New custom strategy (`CustomStrategy`), indicator (`CustomIndicator`), and data feed (`CustomData`)**
All three classes were designed to flexibly take in any column from …
> [FEATURE] Custom indicator support for forecasting use cases

- python/fastquant/backtest/backtest.py
- python/fastquant/strategies/base.py
Take note of the following details:
1. **`backtest` via `BaseStrategy` has two new arguments (set to `None` by default):** `stop_loss` and `stop_trail`.
2. **`stop_loss` means that you set the trigger price as a fixed percentage** of the price at which the asset was purchased (details [here](https://www.backtrader.com/blog/posts/2018-02-01-stop-trading/stop-trading/))
3. **`stop_trail` means that you apply a trailing percentage loss, that follows the price as it goes up** (details [here](https://www.backtrader.com/blog/posts/2018-02-01-stop-trading/stop-trading/))
4. **We now add a dummy "open" column to the input dataframe if a "close" column exists, but an "open" column doesn't.** This means we assume that when no open column exists, the next day open is equal to the current day close, …
> Implement stop loss

- Dockerfile
- README.md
This PR creates a Dockerfile for fastquant which will make it easier to setup the package in different machines (resolving issue #242). 
A particular immediate use case is when fastquant has to be run, and eventually deployed on multiple servers. Personally, I'm already using this for running fastquant experiments in different VM's.
> Create Dockerfile for fastquant environment

- README.md
solves #246 by adding more info that the old quickstart can't be recreated due to sentiments and data dates inconsistencies. added a new quickstart with new `current_date` and `delta_date`.
> add more info on sentiment quickstart

- python/fastquant/data/stocks/stocks.py
- python/fastquant/portfolio.py
- python/tests/test_fastquant.py
just refactored get_stock_data to default in yahoo finance.
default format for yahoo data is `ohlcv` and if the ticker is not found in yf it goes to phisix with format of `c`
closes #235
> refactor get-stock-data to default in yf

- python/fastquant/backtest/backtest.py
Resolves #254
Add risk metrics to backtesting results of backtests on trading stategies. This is an ongoing pull request for the following metrics:
1. Sharpe ratio - Measure of statistical significance of the return of investment given a risk free rate (default in package is 1%)
2. Drawdown - Measure of how low the asset price went before recovery relative to the overall price
3. Drawdown for a specified time period - Measure of the above within a time period specified by the user
> Add risk management analyzers

- python/fastquant/backtest/backtest.py
*Note that it also includes the strat_id and strat_name fields, similar to the rest of the history dataframes.*
Sample usage:
```
from fastquant import get_stock_data, backtest
df = get_stock_data("TSLA", "2019-01-10", "2019-05-01")
res, hist = backtest("smac", df, return_history=True)
print(hist["indicators"])
```
> Add indicator history to resolve #274

- python/fastquant/strategies/base.py
- python/requirements.txt
**Details**
1. **`add_cash_amount` indicates the amount of cash you want to add to your portfolio at each "add cash date".** Once this cash balance is added, the same `buy_prop` will be used as basis for guiding position sizing for now.
2. **`add_cash_freq` indicates the frequency that you add cash.** Currently you can choose from monthly ("M"), on the first day of the month, weekly ("W"), on Monday, or a custom cron notation that indicates your cadence of choice (e.g. 0 0 5 * * for montly on the fifth day of the week).
3. **In the case that the next add cash date lies on a day not contained in the input time series** (e.g. a weekend), the algo will assume the cash inflow is added on the earliest next date (e.g. if the add cash date is Nov 1 which is a weekend, Sunday, with no data, the …
> Add periodic "income" feature to resolve #215

- python/fastquant/backtest/backtest.py
- python/fastquant/backtest/data_prep.py
- python/fastquant/backtest/post_backtest.py
- python/fastquant/indicators/backtrader_indicators.py
- python/fastquant/strategies/mappings.py
- python/tests/test_strategies.py
- Added `figsize` to backtest to adjust plot
- This will allow `backtest()` to focus more on strategies,  analyzers, and performance improvements  
- Moved the following components into a separate file: (data preparation, metrics, plotting)
- To add data validation here
- Allow fine tuning data
- This handles metrics and parameters for strategy optmization
- Separated end-of-backtest plotting logic outside the `backtesting` functionality
> Refactor backtest components into: data preparation, metrics, and plotting

- python/fastquant/backtest/backtest.py
- python/fastquant/backtest/backtest_indicators.py
- python/fastquant/backtest/post_backtest.py
- python/fastquant/indicators/backtrader_indicators.py
History of indicators can now support multiple lines.
Indicators like `BollingerBands` will have three lines instead of one
`BollingerBands_mid_20_0.2`
`BollingerBands_top_20_0.2`
`BollingerBands_bot_20_0.2`
Multi-line indicator support is listed in `python/fastquant/backtest/backtest_indicators.py`
> Updated indicator history to support multiple lines

- .travis.yml
Since we're no longer supporting R this should be fine.
> Take out R tests from travis

- python/fastquant/backtest/backtest.py
- python/fastquant/backtest/data_prep.py
- python/fastquant/backtest/post_backtest.py
There's a new `data_class` argument in `backtest` that allows you to edit the parent class used for `CustomData`#297.
This should allow for greater flexibility on the characterstics of the data object used.
Also included is a fix to allow for dynamic date ranges when extracting historical indicators post backtest #299.
> Add custom data_class to resolve #297

- python/fastquant/backtest/backtest.py
This PR fills in the docstring gaps left in the backtest module. Should be ready to be used for the docs website cc @jgendrinal :smile:
Also, note that I've decided to remove the `data_format` argument from this PR to resolve #312, since this is already automatically handled by `backtest`. We've been intending to deprecate it since ~6 months ago so pulling it out here.
> Complete docstring in backtest module to resolve #291 and remove support for data_format argument (now automatic).

- python/fastquant/data/stocks/stocks.py
Quick fix for the JFC issue where yahoo finance has a conflicting symbol. Since JFC is the flagship example, I've decided to default to `get_pse_data` from `get_stock_data` when `JFC` is the ticker.
> Fix #296 by ensuring JFC defaults to PSE

- python/fastquant/data/crypto/crypto.py
- python/fastquant/data/stocks/stocks.py
This will allow us to access the input parameters straight from the dataframe object.
This will be useful at the `backtest` level, so that the `start_date`, `end_date`, and `symbol` doesn't have to be manually input.
> Set get data parameters as attributes to the output dataframe

- API.md
- README.md
- python/fastquant/backtest/backtest.py
- python/fastquant/backtest/post_backtest.py
Sometimes, users might want to save the plot being created. I added `return_plot` argument to the function `backtest`. 
Now, users should be able to return a dataframe and a plot when calling `backtest(return_plot=True)`
I also added the documentation for fastquant API. Let me know if you would like me to edit, add, or delete anything.
> Return plot

- python/fastquant/backtest/backtest.py
- python/fastquant/backtest/post_backtest.py
Allow users to add arguments to the function `cerebro.plot()` by specifying `plot_kwargs=dictionary_of_items`. I have added the document for this in `backtest` function. But let me know if you need me to add the document for this in any other markdown files
```python
backtest(cfg.strategy.name, df, 
plot_kwargs={'fmt_x_ticks': '%Y-%b-%d %H:%M', #  Format string for the display of ticks on the x axis
'fmt_x_data': '%Y-%b-%d %H:%M'},  # Format string for the display of data points values  
```
> Add plot arguments

- python/fastquant/strategies/rsi.py
Allow users to customize `upperband` and `lowerband` when using rsi strategy.
> add upperband lowerband to rsi indicator

- python/fastquant/config.py
commission is typically 0.075%, not 0.75% and that's a little misleading when doing backtesting without taking care of this default parameter
> More realistic fees

- .gitignore
- python/fastquant/data/crypto/crypto.py
A quick peruse over the issues didn't seem to have anyone requesting this, but most exchanges only return a limited set of results. 
This change goes through in a result size agnostic manner and requests subsequent results. 
Should there not be results all the way to the end date, that is detected, and the end date for the data set is update to reflect the actual range retrieved.
(Not sure if I'm hitting this one - requesting it from a fork)
(There was nothing in the docs to indicate it didn't return the requested range, so the code just now better reflects the docs as they are.
> Pull full requested date range in crypto through paged requests

- python/requirements.txt
With the previous fastquant version, matplotlib would have an error of `ImportError Cannot import name 'warnings' from 'matplotlib.dates` when trying to plot.
This was fixed in the previous PR by [changing matplotlib to 3.2.2.](https://stackoverflow.com/questions/63471764/importerror-cannot-import-name-warnings-from-matplotlib-dates) However, this was committed to be `matplotlib==3.2.2` which may cause issues in pip installs.
This PR changes the matplotlib version to >= 3.2.2. If you get the error stated above, one fix would be to change the version to ==3.2.2.
> Change matplotlib version to require strictly 3.2.2

- examples/2022-02-24-backtest_crypto_exit.ipynb
- python/fastquant/strategies/base.py
Currently, to exit a position, one needs to get a separate sell (if long). This adds separate checks for an exit signal in `exit_long_signal` and `exit_short_signal`
> Add separate Exit signal logic

- .github/workflows/py-cli.yml
- python/requirements.txt
- python/tests/test_fastquant.py
Currently the requirements.txt file requires pandas to have `pandas==1.1.5`. We are changing this to allow `pandas>=1.1.5`. Since yfinance upgraded its pandas, we want to allow for the upgrade as well.
> Remove pandas == dependency

- setup.py
Currently the version in setup.py does not match the pypi and it is very much delayed. This PR is mainly a aesthetic PR to ensure that the pypi version will match the main repo.
> Adjust pypi version in setup.py
